# Generated by Django 4.0.4 on 2022-05-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_mame', models.CharField(max_length=150, verbose_name='Наименование заказчика')),
                ('customers_contact_person', models.CharField(max_length=250, verbose_name='Контактное лицо')),
                ('customers_address', models.CharField(max_length=150, verbose_name='Адрес заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['customers_mame'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_goods', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('date_of_contract', models.DateField(verbose_name='Дата подписания договора')),
                ('date_of_delivery', models.DateField(verbose_name='Дата поставки')),
                ('contract_status', models.CharField(max_length=150, verbose_name='Состояние заказа')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordering.customers', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_of_contract'],
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(blank=True, upload_to='docs/%Y/%m/%d/', verbose_name='Документы')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordering.orders', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('author', models.CharField(max_length=150, verbose_name='Автор комментария')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordering.requirements', verbose_name='Требования')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
