# Generated by Django 4.0.4 on 2022-05-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_requirements_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-date_of_contract'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={'ordering': ['id'], 'verbose_name': 'Тех. требования', 'verbose_name_plural': 'Тех. требования'},
        ),
    ]
