# Generated by Django 4.0.4 on 2022-05-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_alter_orders_options_alter_requirements_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='requirements',
        ),
        migrations.AddField(
            model_name='comments',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ordering.orders', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
